### ISSUE TITLE
Lagerverwaltung für Uniformteile

### ISSUE THREAD

**Issue by tn02103** [tn02103/uniformAdministrationApp#34]
## Beschreibung
Uniformteile werden, immer wieder in Kisten gelagert. Momentan müssen die Kistennummern in die Kommentarfunktion der Uniformteile eingetragen werden. In Zukunft sollte hierfür ein besseres Konzept Ausgearbeitet werden, in dem die Kisten auch in dem Programm wiedergespiegelt werden können, und das Zuordnen der UTs zu den Kisten deutlich einfacher geht. 

### Noch abzuklären:
- Sind die StorageUnits primär für Uniformteile in Reserve oder könnte man sich vorstellen dies auch vermehrt für aktive Uniformteile zu Nutzen?

Im ersten Schritt sollten die StorageUnits für Uniformteile in Reserve sein. Weitere Features um diese auch bequemer für die aktiven Uniformteile zu nutzen, werden nur nach Bedarf zu einem späteren Zeitpunkt erstellt. 
- Sollen StorageUnits primär nur für ein Uniformtyp sein, oder auch für mehrere?
- Was passiert wenn ein Uniformteil ausgegeben wird, welches einer Unit zugeordnet ist?

Option 1: Der Nutzer bekommt eine Warnmeldung ausgegeben und muss das ausgeben des UTs aktiv bestätigen. 
Option 2: Der Nutzer bekommt kein Hinweis darauf, dass das Uniformteil aus einer StorageUnit kommt. 
Beide Optionen: Das Uniformteil ist nicht weiter der StorageUnit zugeordnet. 
- Wann sollen Uniformteile auf Reserve gesetzt werden?

Die StorageUnits sollen ein Parameter haben, über welchen Bestimmt wird, ob das Zuordnen eines Uniformteils automatisch dazu führt, dass das UT als Reserve markiert wird. Diese Markierung wird beim Entfernen des Uniformteils von der StorageUnit **nicht** wieder zurück gesetzt

~~Wenn die Units für die aktiven Uniformteile genutzt werden sind vollgende Punkte zu überlegen:~~
~~- [ ] Automatisches einordner von Uniformteilen in eine standard-StorageUnit, wenn es vom VK zurückgegeben wird?~~
~~- [ ] Kann eine Storage-Unit nur für ein Uniformtype der Standard sein?~~

#### StorageUnit
- **Id**: string (Automatisch generierte uuid)
- **Name**: string (max ?20? Zeichen, Muss pro Organisation einzigartig sein)
- **Description**: string (max ?50? Zeichen, Ist optional. Kann genutzt werden um Inhalt/ Nutzen näher zu Beschreiben)
- **?isReserve?**: boolean (Evtl. Umbenenung. Soll definieren, ob UT die dieser Unit zugeordnet werden automatisch als "isReserve" markiert werden
- **capacity**: number (max 100, optional, kann dafür genutzt werden um ein Limit zu definieren, wie viele UT hier hinzugefügt werden sollen. Überschreibung nur wenn Nutzer bestätigt)
- **assosiationId**: string, (Id der Organisation) 
- **uniformList**: Liste der Zugeordneten Uniformteile

#### Uniform
- ~~active~~ **isReserve**, boolean (umbenenung um Nutzen besser wieder zu spiegeln, soll auch in den Angezeigten Texten passieren.
- **storageUnitId**, string|null, (id der zugeordneten StorageUnit)
- **storageUnit**, die Zogeordnete StorageUnit

### Abnahmekriterien
- [ ] Erstellen neuer StorateUnits möglich
- [ ] Löschen von StorageUnits möglich
- [ ] Bearbeiten von StorageUnits möglich
- [ ] Hinzufügen von Uniformteilen über die Configseite möglich
- [ ] Entfernen von Uniformteilen über die Configseite möglich
- [ ] Hinzufügen eines Uniformteils über die Uniformdetail-Komponente möglich
- [ ] Entfernen eines Uniformteils über die Uniformdetiail-Komponente möglich
- [ ] Hinzufügen eines Uniformteils nur wenn es nicht ausgegeben ist.
- [ ] StorageUnit der Uniformteile werden in der Uniformlisten-Seite mit angezeigt
- [ ] Warnung wenn StorageUnit zu voll ist
- [ ] Markieren überfüllter StorageUnits
- [ ] Beim Löschen eines Uniformteils, wird es dem der StorageUnit entzogen. (Das Löschen passiert an mehreren Stellen (deleteUniformItem, deleteUniformType ??))
<br/><br/>
### Erstellen
Ein Materialverwalter kann eine neue StorageUnit erstellen. 
#### Kriterien
- [ ] Es wird verhindert, dass zwei Units einer Organisation den selben Namen haben
<hr/>

### Bearbeiten einer StorageUnit
Asl Materialverwalter möchte ich die Daten einer StorageUnit verändern können
#### Kriterien:
- [ ] Die Parameter (name, description, capacity, isForReserve) können verändert werden
- [ ] Beim Speichern wird überprüft, das der Name noch nicht von einer anderen Unit benutzt wird
<hr/>

### Löschen einer Storageunit
Als Materialverwalter möchte ich eine StorageUnit wieder löschen können. Hierbei muss ich diese Aktion im vorhinein bestätigen. (Keine Option für DAL-Methode nötig, da Bestätigung im Frontend immer passieren muss)
#### Kriterien:
- [ ] storageUnitId wird für alle Uniformteile dieser StorageUnit auf null gesetzt. 
- [ ] unit wird entgültig aus der Datenbank gelöscht
<hr/>

### Hinzufügen eines Uniformteils
Als Materialveralter kann ich ein Uniformteil einer StorageUnit zuteilen. 
#### Orte:
- [ ] In der Uniformdetail-Komponente, kann das ausgewählte Uniformteil einer StorageUnit zugeordnet werden.
- [ ] In der StorageUnit-Konfigurationskomponente, können mehrere Uniformteile über eine Suchkomponente hinzugefügt werden
#### Kriterien
- [ ] Uniformteil darf nicht vergeben sein
- [ ] Uniformteil darf keiner anderen StorageUnit zugeteilt sein
- [ ] Wenn die StorageUnit voll ist, muss die Option "ignoreFull" wahr sein (Bestätigung des Nutzers benötigt)
- [ ] Wenn die StorageUnit keine Kapazität hinterlegt hat, gibt es keinen Check ob diese Voll ist.
- [ ] Wenn die StorageUnit für die Reserve ist, wird das Uniformteil als isReserve markiert, es ist abgeklärt, ob das der Nutzer diese Aktion im vorhinein noch bestätigen soll. Wenn ja wird eine weitere option hierfür benötigt. 
<hr/>

### Entfernen eines Uniformteils
Als Materialverwalter möchte ich ein Uniformteil einer StorageUnit wieder entziehen
#### Kriterien:
- die storageUnitId des Uniformteils wird auf null gesetzt
<hr/>

### Ausgeben eines Uniformteils
Als Inspector möchte ich daruf hingewiesen werden, wenn ein Uniformteil einer StorageUnit zugeordnet ist. Ist das Uniformteil noch als Reserve gekennzeichnet, sollen beide Informationen in einem Dialog zusammen angezeigt werden. 
#### Kriterien:
- Ist das Uniformteil einer StorageUnit zugeordnet, so wird ein Error-Objekt zurückgegeben. 
- Ist die option.resolveStorage gesetzt, wird das Uniformteil der Storageunit entzogen und kein Fehler zurückgegeben.
- Der Fehler der DAL-Methode beinhaltet die Informationen (storageUnit: StorageUnit, passiv: boolean)
<hr/>

### Löschen eines Uniformteils
Als Inspector möchte ich ein Uniformteil ohne Probleme löschen können. (In der DB nur als gelöscht markiert)
#### Kriterien:
- der Wert storageUnitId wird beim Löschvorgang auf null gesetzt
